# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables for MySQL configuration
ENV ENGINE=mysql.connector.django
ENV ROOT_PASSWORD=1234
ENV HOST=mysql
ENV NAME=app_db
ENV DATABASE=app_db
ENV USER=app_user
ENV PASSWORD=1234
ENV PORT=3307

# Expose port 3306 for MySQL connections
EXPOSE 3307

# Set the data directory as a volume
VOLUME /var/lib/mysql
