# docker-compose.yml

version: '2.0.2'
networks:
  todoapp-net:

services:
  pythonapp:
    image: todoapp:2.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql-local:2.0.1
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3307:3307"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - ENGINE=mysql.connector.django
      - NAME=app_db
      - USER=app_user
      - PASSWORD=1234
      - HOST=mysql
      - PORT=3307
    networks:
      - todoapp-net

volumes:
  todoapp-db-data:
